"""Add quote lifecycle hardening

Revision ID: 57d158d4b99b
Revises: cd6b5849d7a0
Create Date: 2026-06-03 16:53:39.540683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57d158d4b99b'
down_revision: Union[str, Sequence[str], None] = 'cd6b5849d7a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes_v2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_status_history_id'), 'quote_status_history', ['id'], unique=False)
    op.add_column('quotes_v2', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('quotes_v2', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quotes_v2', 'users', ['approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quotes_v2', type_='foreignkey')
    op.drop_column('quotes_v2', 'approved_by')
    op.drop_column('quotes_v2', 'approved_at')
    op.drop_index(op.f('ix_quote_status_history_id'), table_name='quote_status_history')
    op.drop_table('quote_status_history')
    # ### end Alembic commands ###
