"""phase_85_materials_surface_finishes_setting_audit_customer_update

Revision ID: 78df2fa13118
Revises: ac2a628829fb
Create Date: 2026-06-12 13:48:51.548213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78df2fa13118'
down_revision: Union[str, Sequence[str], None] = 'ac2a628829fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_rate_bands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_name', sa.String(), nullable=False),
    sa.Column('thickness_min', sa.Float(), nullable=False),
    sa.Column('thickness_max', sa.Float(), nullable=False),
    sa.Column('rate_low', sa.Float(), nullable=False),
    sa.Column('rate_high', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_rate_bands_id'), 'material_rate_bands', ['id'], unique=False)
    op.create_index(op.f('ix_material_rate_bands_material_name'), 'material_rate_bands', ['material_name'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('density', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_index(op.f('ix_materials_name'), 'materials', ['name'], unique=True)
    op.create_table('setting_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setting_audit_id'), 'setting_audit', ['id'], unique=False)
    op.create_index(op.f('ix_setting_audit_setting_key'), 'setting_audit', ['setting_key'], unique=False)
    op.create_table('surface_finishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surface_finishes_id'), 'surface_finishes', ['id'], unique=False)
    op.create_index(op.f('ix_surface_finishes_name'), 'surface_finishes', ['name'], unique=True)
    op.create_table('material_thicknesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('thickness_mm', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'thickness_mm', name='uq_material_thickness')
    )
    op.create_index(op.f('ix_material_thicknesses_id'), 'material_thicknesses', ['id'], unique=False)
    op.create_index(op.f('ix_material_thicknesses_material_id'), 'material_thicknesses', ['material_id'], unique=False)
    op.add_column('customers', sa.Column('website', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('lead_source', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'updated_at')
    op.drop_column('customers', 'notes')
    op.drop_column('customers', 'lead_source')
    op.drop_column('customers', 'website')
    op.drop_index(op.f('ix_material_thicknesses_material_id'), table_name='material_thicknesses')
    op.drop_index(op.f('ix_material_thicknesses_id'), table_name='material_thicknesses')
    op.drop_table('material_thicknesses')
    op.drop_index(op.f('ix_surface_finishes_name'), table_name='surface_finishes')
    op.drop_index(op.f('ix_surface_finishes_id'), table_name='surface_finishes')
    op.drop_table('surface_finishes')
    op.drop_index(op.f('ix_setting_audit_setting_key'), table_name='setting_audit')
    op.drop_index(op.f('ix_setting_audit_id'), table_name='setting_audit')
    op.drop_table('setting_audit')
    op.drop_index(op.f('ix_materials_name'), table_name='materials')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_material_rate_bands_material_name'), table_name='material_rate_bands')
    op.drop_index(op.f('ix_material_rate_bands_id'), table_name='material_rate_bands')
    op.drop_table('material_rate_bands')
    # ### end Alembic commands ###
