"""Add phase 8 instant estimate fields to RFQ

Revision ID: ac2a628829fb
Revises: a1b2c3d4e5f6
Create Date: 2026-06-11 15:11:43.299174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac2a628829fb'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quote_item_svg_cache', 'generated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('quote_item_svg_cache_rfq_file_id_key'), 'quote_item_svg_cache', type_='unique')
    op.drop_constraint(op.f('quote_item_svg_cache_rfq_file_id_fkey'), 'quote_item_svg_cache', type_='foreignkey')
    op.create_foreign_key(None, 'quote_item_svg_cache', 'rfq_files', ['rfq_file_id'], ['id'])
    op.drop_constraint(op.f('fk_quote_items_rfq_file_id'), 'quote_items', type_='foreignkey')
    op.create_foreign_key(None, 'quote_items', 'rfq_files', ['rfq_file_id'], ['id'])
    op.add_column('rfqs', sa.Column('lead_source', sa.String(), server_default='Manual Upload', nullable=False))
    op.add_column('rfqs', sa.Column('material', sa.String(), nullable=True))
    op.add_column('rfqs', sa.Column('thickness', sa.Float(), nullable=True))
    op.add_column('rfqs', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('rfqs', sa.Column('estimate_min', sa.Float(), nullable=True))
    op.add_column('rfqs', sa.Column('estimate_max', sa.Float(), nullable=True))
    op.add_column('rfqs', sa.Column('estimate_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rfqs', 'estimate_date')
    op.drop_column('rfqs', 'estimate_max')
    op.drop_column('rfqs', 'estimate_min')
    op.drop_column('rfqs', 'quantity')
    op.drop_column('rfqs', 'thickness')
    op.drop_column('rfqs', 'material')
    op.drop_column('rfqs', 'lead_source')
    op.drop_constraint(None, 'quote_items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_quote_items_rfq_file_id'), 'quote_items', 'rfq_files', ['rfq_file_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'quote_item_svg_cache', type_='foreignkey')
    op.create_foreign_key(op.f('quote_item_svg_cache_rfq_file_id_fkey'), 'quote_item_svg_cache', 'rfq_files', ['rfq_file_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('quote_item_svg_cache_rfq_file_id_key'), 'quote_item_svg_cache', ['rfq_file_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('quote_item_svg_cache', 'generated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
