"""Add Phase 6 Estimate and Quote models

Revision ID: cd6b5849d7a0
Revises: bd5c03f95bb9
Create Date: 2026-06-03 16:19:22.013735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd6b5849d7a0'
down_revision: Union[str, Sequence[str], None] = 'bd5c03f95bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_table('quotes_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_number', sa.String(), nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('margin_amount', sa.Float(), nullable=False),
    sa.Column('gst_amount', sa.Float(), nullable=False),
    sa.Column('grand_total', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_v2_id'), 'quotes_v2', ['id'], unique=False)
    op.create_index(op.f('ix_quotes_v2_quote_number'), 'quotes_v2', ['quote_number'], unique=True)
    op.create_table('quote_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('part_name', sa.String(), nullable=False),
    sa.Column('material', sa.String(), nullable=False),
    sa.Column('thickness', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('material_cost', sa.Float(), nullable=False),
    sa.Column('cutting_cost', sa.Float(), nullable=False),
    sa.Column('bending_cost', sa.Float(), nullable=False),
    sa.Column('welding_cost', sa.Float(), nullable=False),
    sa.Column('machining_cost', sa.Float(), nullable=False),
    sa.Column('labour_cost', sa.Float(), nullable=False),
    sa.Column('part_total', sa.Float(), nullable=False),
    sa.Column('material_rate_snapshot', sa.Float(), nullable=False),
    sa.Column('laser_rate_snapshot', sa.Float(), nullable=False),
    sa.Column('bending_rate_snapshot', sa.Float(), nullable=False),
    sa.Column('welding_rate_snapshot', sa.Float(), nullable=False),
    sa.Column('machining_rate_snapshot', sa.Float(), nullable=False),
    sa.Column('labour_rate_snapshot', sa.Float(), nullable=False),
    sa.Column('margin_snapshot', sa.Float(), nullable=False),
    sa.Column('gst_snapshot', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes_v2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_items_id'), 'quote_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_items_id'), table_name='quote_items')
    op.drop_table('quote_items')
    op.drop_index(op.f('ix_quotes_v2_quote_number'), table_name='quotes_v2')
    op.drop_index(op.f('ix_quotes_v2_id'), table_name='quotes_v2')
    op.drop_table('quotes_v2')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
