"""Add archive fields to RFQFile

Revision ID: fdc00e292a5e
Revises: 78df2fa13118
Create Date: 2026-06-12 16:17:15.613420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc00e292a5e'
down_revision: Union[str, Sequence[str], None] = '78df2fa13118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rfq_files', sa.Column('storage_status', sa.String(), server_default='active', nullable=False))
    op.add_column('rfq_files', sa.Column('archived_at', sa.DateTime(), nullable=True))
    op.add_column('rfq_files', sa.Column('archived_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rfq_files', 'archived_reason')
    op.drop_column('rfq_files', 'archived_at')
    op.drop_column('rfq_files', 'storage_status')
    # ### end Alembic commands ###
